INSERT INTO Modele (constructeur) VALUES ('AMC');
INSERT INTO Modele (constructeur) VALUES ('Acura');
INSERT INTO Modele (constructeur) VALUES ('Alfa Romeo');
INSERT INTO Modele (constructeur) VALUES ('Alpina');
INSERT INTO Modele (constructeur) VALUES ('Ariel');
INSERT INTO Modele (constructeur) VALUES ('Aston Martin');
INSERT INTO Modele (constructeur) VALUES ('Auburn');
INSERT INTO Modele (constructeur) VALUES ('Audi');
INSERT INTO Modele (constructeur) VALUES ('Austin');
INSERT INTO Modele (constructeur) VALUES ('BMW');
INSERT INTO Modele (constructeur) VALUES ('Bentley');
INSERT INTO Modele (constructeur) VALUES ('Bugatti');
INSERT INTO Modele (constructeur) VALUES ('Buick');
INSERT INTO Modele (constructeur) VALUES ('Cadillac');
INSERT INTO Modele (constructeur) VALUES ('Chevrolet');
INSERT INTO Modele (constructeur) VALUES ('Chrysler');
INSERT INTO Modele (constructeur) VALUES ('Citroen');
INSERT INTO Modele (constructeur) VALUES ('Cord');
INSERT INTO Modele (constructeur) VALUES ('Desota');
INSERT INTO Modele (constructeur) VALUES ('Dodge');
INSERT INTO Modele (constructeur) VALUES ('FPV');
INSERT INTO Modele (constructeur) VALUES ('Fiat');
INSERT INTO Modele (constructeur) VALUES ('Ford');
INSERT INTO Modele (constructeur) VALUES ('GMC');
INSERT INTO Modele (constructeur) VALUES ('HSV');
INSERT INTO Modele (constructeur) VALUES ('Hennessey');
INSERT INTO Modele (constructeur) VALUES ('Henry J');
INSERT INTO Modele (constructeur) VALUES ('Holden');
INSERT INTO Modele (constructeur) VALUES ('Honda');
INSERT INTO Modele (constructeur) VALUES ('Hummer');
INSERT INTO Modele (constructeur) VALUES ('Hyundai');
INSERT INTO Modele (constructeur) VALUES ('Kia');
INSERT INTO Modele (constructeur) VALUES ('Lamborghini');
INSERT INTO Modele (constructeur) VALUES ('Lasalle');
INSERT INTO Modele (constructeur) VALUES ('Lexus');
INSERT INTO Modele (constructeur) VALUES ('Lincoln');
INSERT INTO Modele (constructeur) VALUES ('Lotus');
INSERT INTO Modele (constructeur) VALUES ('Maruti');
INSERT INTO Modele (constructeur) VALUES ('Maserati');
INSERT INTO Modele (constructeur) VALUES ('Mazda');
INSERT INTO Modele (constructeur) VALUES ('McLaren');
INSERT INTO Modele (constructeur) VALUES ('Mercedes-Benz');
INSERT INTO Modele (constructeur) VALUES ('Mercury');
INSERT INTO Modele (constructeur) VALUES ('Mistubishi');
INSERT INTO Modele (constructeur) VALUES ('Nissan');
INSERT INTO Modele (constructeur) VALUES ('Oldsmobile');
INSERT INTO Modele (constructeur) VALUES ('Packard');
INSERT INTO Modele (constructeur) VALUES ('Pagani');
INSERT INTO Modele (constructeur) VALUES ('Perodua');
INSERT INTO Modele (constructeur) VALUES ('Peugeot');
INSERT INTO Modele (constructeur) VALUES ('Pierce Arrow');
INSERT INTO Modele (constructeur) VALUES ('Plymouth');
INSERT INTO Modele (constructeur) VALUES ('Pontiac');
INSERT INTO Modele (constructeur) VALUES ('Porsche');
INSERT INTO Modele (constructeur) VALUES ('Renault');
INSERT INTO Modele (constructeur) VALUES ('Rolls Royce');
INSERT INTO Modele (constructeur) VALUES ('Saleen');
INSERT INTO Modele (constructeur) VALUES ('Saturn');
INSERT INTO Modele (constructeur) VALUES ('Shelby');
INSERT INTO Modele (constructeur) VALUES ('Skoda');
INSERT INTO Modele (constructeur) VALUES ('Smart4two');
INSERT INTO Modele (constructeur) VALUES ('Studebaker');
INSERT INTO Modele (constructeur) VALUES ('Subaru');
INSERT INTO Modele (constructeur) VALUES ('Suzuki');
INSERT INTO Modele (constructeur) VALUES ('Tata');
INSERT INTO Modele (constructeur) VALUES ('Tesla');
INSERT INTO Modele (constructeur) VALUES ('Toyota');
INSERT INTO Modele (constructeur) VALUES ('Volks Wagen');
