	<div id="page">
		<h1><?php echo $title; ?></h1>
		<?php
			if (isset($profile) && ($profile->_pseudo != NULL)) {
		?>
		<input id="profile_view" class="boutons" type="button" value="Rafraichir le mur" onClick="updateWall()" />
		<?php
			}
		?>
		<div id="description">
			<p><?php echo $pageInfos['description']; ?></p>
		</div>
		<div id="update">
		</div>
		<div id="profil">
		<?php 	
			if (isset($_GET['id'])) {
				if ($profile->_pseudo != NULL) {
		?>
			<table class="profil">
				<tr>
					<th>Pseudo</th>
					<th>Email</th>
					<th>Sexe</th>
					<th>Description</th>
					<th>Website</th>
					<th>Photo</th>
				</tr>
				<tr>
					<td><?php echo $profile->_pseudo; ?></td>
					<td><?php echo $profile->_email; ?></td>
					<td id="sexe"><?php echo $profile->_sex; ?></td>
					<td id="description"><?php echo $profile->_description; ?></td>
					<td><a href="<?php echo $profile->_website; ?>"><?php echo $profile->_website; ?></a></td>
					<td><?php echo "<img src='{$profile->_image}' />"; ?></td>
				</tr>
			</table><br />
			<h2>Ses statuts</h2>
		<?php
					if ($updates != false) {
		?>
			<table class="trois_freres">
				<tr>
					<th>Date</th>
					<th>Statut</th>
					<th>Service</th>
				</tr>
		<?php
						foreach ($updates as $update) {
		?>
				<tr>
					<td><?php echo $update['date'];?></td>
					<td><?php echo $update['content'];?></td>
					<td><?php echo $update['service'];?></td>
				</tr>
		<?php
						}
		?>
			</table><br />
		<?php
					}
					else {
		?>
			<p>Aucun statut enregistre pour ce profil.</p>
		<?php
					}
		?>
			<h2>Ses videos preferees</h2>
		<?php
					if ($videos != false) {
		?>
			<table class="profil">
				<tr>
					<th>Date</th>
					<th>Image</th>
					<th>Titre</th>
					<th>Url</th>
				</tr>
		<?php
						foreach ($videos as $video) {
		?>
				<tr>
					<td><?php echo $video['date'];?></td>
					<td><img src="<?php echo $video['image'];?>" /></td>
					<td><?php echo $video['title'];?></td>
					<td><a href="<?php echo $video['url'];?>"><?php echo $video['url'];?></a></td>
				</tr>
		<?php
						}
		?>
			</table><br />
		<?php
					}
					else {
		?>
			<p>Aucune video enregistree pour ce profil.</p>
		<?php
					}
				}
				else {
		?>
			<p>Ce profil n'existe pas.</p><br />
		<?php
				}
			}
		?>
			<form method="get" action="view">
				<table class="afficher_profil">
					<tr>
						<td><label>Indiquez l'ID du membre a afficher :</label></td>
						<td><input class="id" name="id" type="text" /></td>
					</tr>
				</table>
				<input id="afficher_profil" class="boutons" type="submit" value="Afficher" />
			</form>
		</div>
