<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
    <head>
    <title>DataPhoneAuto Mobile</title>
    <link rel="stylesheet"
href="http://code.jquery.com/mobile/1.0a2/jquery.mobile-1.0a2.min.css" />
    <script type="text/javascript"
src="http://code.jquery.com/jquery-1.4.3.min.js">
</script>		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script type="text/javascript"
src="http://code.jquery.com/mobile/1.0a2/jquery.mobile-1.0a2.min.js">
</script>
</head>


<body>
 
<div data-role="page">
    <div data-role="header">
        <h1>DataPhoneAuto</h1>
    </div><!-- /entete -->
 
    <div data-role="content"> 

	<?php 	
		if (isset($_POST['email'])) {
	?>
		<br /><p>Email et/ou mot de passe incorrect(s).</p><br />
	<?php 	
		} 
	?>

       
<form id="formSignIn" method="post" action="/mobile/index" name="formSignIn" onsubmit="">
	
		
          <div id="email" data-role="fieldcontain">
		        <label for="email">Email</label>		
		        <input id="" class="" name="email" type="text" />
	  </div>
	
	            
          <div id="password" data-role="fieldcontain">
          		<label for="pass">Password</label>		
          		<input id="" class="" name="password" type="password" />
          </div>

          <div id="submitDiv" data-role="fieldcontain">    
          	 <input id="btnConnect" class="" type="submit" value="Connexion" />
          </div>
   </form>
   
   
   
<?php 	
	if (isset($_SESSION['connected']) || ($_SESSION['connected'] == true)) 
	{
?>
        <ul data-role="listview" data-inset="true" data-theme="c" data-dividertheme="a">
		<li data-role="list-divider">Administration</li>
		<li><a href="http://www.google.fr">Mes informations</a></li>
		<li><a href="http://www.google.de">Mes voitures</a></li>
		<li><a href="http://www.google.com">Ajouter une voiture</a></li>
		<li><a href="http://www.google.it">Supprimer une voiture</a></li>
		
	</ul>
<?php 
        }
	else {
?>
	<p>Vous devez etre connecte pour acceder a cette page.</p>
	<p>Vous serez redirige dans 5 secondes ...</p>
	<img id="disconnect" src='../../images/deco.gif' />
<?php
	}
?>

</div><!-- /contenu -->
 
    <div data-role="footer">
        <h4></h4>
    </div><!-- /footer -->
</div><!-- /Fin de la page -->
 
</body>
</html>
