<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
    <head>
    <title>DataPhoneAuto Mobile</title>
    <link rel="stylesheet"
href="http://code.jquery.com/mobile/1.0a2/jquery.mobile-1.0a2.min.css" />
    <script type="text/javascript"
src="http://code.jquery.com/jquery-1.4.3.min.js">
</script>		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script type="text/javascript"
src="http://code.jquery.com/mobile/1.0a2/jquery.mobile-1.0a2.min.js">
</script>
</head>


<body>
 
<div data-role="page">
    <div data-role="header">
        <h1>Mes informations</h1>
    </div><!-- /entete -->
 
    <div data-role="content"> 


   <!-- /contenu -->



</div><!-- /contenu -->
 
    <div data-role="footer">
        <h4></h4>
    </div><!-- /footer -->
</div><!-- /Fin de la page -->
 
</body>
</html>
