	<?php
		//if ($fail == true) {
	?>
	<!--<p id="try_connect">Pseudo et/ou mot de passe incorrect(s).</p>-->
	<?php
		//}
	?>
	<div id="">
		<!-- TITRE PAGE -->
		<h1><?php echo $pageInfos['titre']; ?></h1>
		<!-- FIN TITRE PAGE -->
		<!-- DESCRIPTION PAGE -->
		<div id="description">
			<p><?php echo $pageInfos['description']; ?></p>
		</div>
		<!-- FIN DESCRIPTION PAGE -->
		<div id="">
		</div>
	</div>
