	<div id="">
		<h1><?php echo $pageInfos['titre']; ?></h1>
		<div id="description">
			<p><?php echo $pageInfos['description']; ?></p>
		</div>
		<div id="lostPass">
		<?php 	
			if (isset($_POST['email'])) {
			if($member->_idMember != NULL){
		?>
			<br /><p>Message envoy&eacute;.</p><br />
		<?php 
			}else{
		?>
		<br /><p>Cet email n'&eacutexiste pas.</p><br />
		<?php 
		}
		}
		?>
			
			<form id="formLostPass" method="post" action="/members/lostpass" name="formLostPass" onsubmit="">
				<table class="tableLostPass">
					<tr>
						<td><label>Email :</label></td>
						<td><input id="" class="" name="email" type="text" tabindex="1" /></td>
					</tr>
				</table>
				<input id="btnConnect" class="" type="submit" value="Envoyer" />
			</form>
		</div>
	</div>
