	<div id="">
		<h1><?php echo $pageInfos['titre']; ?></h1>
		<div id="description">
			<p><?php echo $pageInfos['description']; ?></p>
		</div>
		<div id="signIn">
		<?php 	
			if (isset($_POST['email'])) {
		?>
			<br /><p>Email et/ou mot de passe incorrect(s).</p><br />
		<?php 	
			} 
		?>
			<form id="formSignIn" method="post" action="/members/signin" name="formSignIn" onsubmit="">
				<table class="tableSignIn">
					<tr>
						<td><label>Email :</label></td>
						<td><input id="" class="" name="email" type="text" tabindex="1" /></td>
					</tr>
					<tr>
						<td><label>Mot de passe :</label></td>
						<td><input id="" class="" name="password" type="password" tabindex="2" /></td>
					</tr>
				</table>
				<input id="btnConnect" class="" type="submit" value="Connexion" />
			</form>
			<br />
			<a href="../members/lostpass">Mot de passe oubli&eacute;?</a>
		</div>
	</div>
