	<?php
		//if ($fail == true) {
	?>
	<!--<p id="try_connect">Pseudo et/ou mot de passe incorrect(s).</p>-->
	<?php
		//}
	?>
	<div id="">
		<!-- TITRE PAGE -->
		<h1><?php echo $pageInfos['titre']; ?></h1>
		<!-- FIN TITRE PAGE -->
		<!-- DESCRIPTION PAGE -->
		<div id="description">
			<p><?php echo $pageInfos['description']; ?></p><br/>
			<div id="video">
				<h3>Vous pouvez également télécharger notre vid&eacute;o <a href="../../images/I4-VIDEO-PPE1142.mp4" target=_blank> ici </a></h3><br />
				<iframe width="560" height="315" src="http://www.youtube.com/embed/cSFZTv_zSz8" frameborder="0" allowfullscreen></iframe>
			</div>
		</div>
		<!-- FIN DESCRIPTION PAGE -->
		<div id="">
		</div>
	</div>
