		<div class="clear"></div>
			<div id="footer">
				<br />
				<p>Geoffroy - Quentin - Guillaume - Antoine - Christian</p>
				<p>ECE - PPE2012 - Data Phone Auto</p>
				<p><ul class="connect">
					<a href="mailto:dataphoneauto@free.fr" class="tip" title="Send us an email"><img src="../images/mail.png" alt="mail" width="32" height="32" /></a>
					
					<a href="http://www.facebook.com/dataphoneauto" class="tip" title="Join us on Facebook" target=_blank><img src="../images/facebook.png" alt="Facebook" width="32" height="32" /></a>

					<a href="http://twitter.com/dataphoneauto" class="tip" title="Follow us on Twitter" target=_blank><img src="../images/twitter.png" alt="Twitter" width="32" height="32" /></a>
				</ul></p>
				<p><script src="http://counter1.compteurdevisite.com/private/counter.js?c=1989a1b67b5734b61d076f5d9f8e84bd"></script>
<noscript>Pour une fonctionalite optimal de votre compteur, ne pas modifier ce code<a href="http://www.compteurdevisite.com" target=_blank>compteur de visite gratuit</a></noscript></p>
			</div>
		</div>
	</body>
</html>
